[workspace]
authors = ["Lukas Hermann <1734032+lsh@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = "glfw-mojo"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[dependencies]
max = ">=25.7.0.dev2025110705,<26"
mojo = ">=0.25.7.0.dev2025110705,<0.26"
