[workspace]
authors = ["Lukas Hermann <1734032+lsh@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = "glfw-mojo"
version = "0.1.0"
description = "GLFW bindings for Mojo"

[package.build]
backend = { name = "pixi-build-mojo", version = "*" }

[package.build-dependencies]
mojo = ">=0.25.7.0.dev2025110505,<0.26"
glfw = ">=3.4,<4"

[package.run-dependencies]
mojo = ">=0.25.7.0.dev2025110505,<0.26"
max = ">=25.7.0.dev2025110505,<26"
glfw = ">=3.4,<4"

[dependencies]
# For development - allows you to work on glfw-mojo itself
glfw-mojo = { path = "." }
